import type { LucideIcon } from 'lucide-react'
import {
  ArrowLeft,
  ArrowRight,
  BedDouble,
  Bird,
  BookOpen,
  BrushCleaning,
  Cat,
  CalendarDays,
  Castle,
  Check,
  CircleCheckBig,
  CircleDot,
  CircleDollarSign,
  CircleX,
  CloudLightning,
  Container,
  CookingPot,
  Crown,
  Dog,
  Droplets,
  Eye,
  FerrisWheel,
  Film,
  Flame,
  Flower2,
  Gift,
  Gamepad2,
  Ghost,
  House,
  Leaf,
  LockKeyhole,
  LogOut,
  Medal,
  Menu,
  Moon,
  Monitor,
  Music2,
  Orbit,
  Palette,
  PawPrint,
  Pencil,
  Pizza,
  Plus,
  Puzzle,
  RotateCcw,
  Salad,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Skull,
  Smartphone,
  Sparkles,
  Star,
  Sword,
  Swords,
  Timer,
  Target,
  TentTree,
  Trash2,
  Trophy,
  Undo2,
  UsersRound,
  Utensils,
  WandSparkles,
  Waves,
  X,
  Zap,
} from 'lucide-react'

/**
 * ChoreQuest stores icon choices as emoji strings for backwards compatibility.
 * Keep this alias table exhaustive so a saved choice never silently turns into
 * a generic sparkle (which makes personalization feel fake).
 */
const ICONS: Record<string, LucideIcon> = {
  '⚔️': Swords,
  '⚔': Swords,
  '🗡️': Sword,
  '🗡': Sword,
  '🛡️': Shield,
  '🛡': Shield,
  '🛏️': BedDouble,
  '🛏': BedDouble,
  '🐱': PawPrint,
  '🐾': PawPrint,
  '📚': BookOpen,
  '🗑️': Trash2,
  '🗑': Trash2,
  '🍽️': Utensils,
  '🍽': Utensils,
  '🍳': CookingPot,
  '🧹': BrushCleaning,
  '🧺': ShoppingBasket,
  '🪣': Container,
  '🚿': ShowerHead,
  '🥗': Salad,
  '💧': Droplets,
  '🚗': House,
  '🌿': Leaf,
  '🖥️': Monitor,
  '🖥': Monitor,
  '⭐': Star,
  '🌟': Star,
  '🔥': Flame,
  '⚡': Zap,
  '🎁': Gift,
  '🔒': LockKeyhole,
  '🪙': CircleDollarSign,
  '✦': Sparkles,
  '✨': Sparkles,
  '🏰': Castle,
  '☠️': Skull,
  '☠': Skull,
  '🌩️': CloudLightning,
  '🌩': CloudLightning,
  '🌙': Moon,
  '🦋': Flower2,
  '🌸': Flower2,
  '🎨': Palette,
  '🧩': Puzzle,
  '🎵': Music2,
  '📖': BookOpen,
  '🔮': Orbit,
  '🧙': WandSparkles,
  '🧙‍♀️': WandSparkles,
  '🧝': Crown,
  '🧝‍♂️': Crown,
  '🧚': Flower2,
  '🦊': Cat,
  '🐉': Swords,
  '🦄': WandSparkles,
  '🧜': Waves,
  '🦸': ShieldCheck,
  '🐺': Dog,
  '🦅': Bird,
  '🧸': PawPrint,
  '🎯': Target,
  '🏆': Trophy,
  '💫': Sparkles,
  '👨‍👩‍👧': UsersRound,
  '👁️': Eye,
  '👁': Eye,
  '🪄': WandSparkles,
  '👾': Ghost,
  '💀': Skull,
  '🦂': CircleDot,
  '👹': Ghost,
  '👿': Skull,
  '🕸️': CircleDot,
  '🕳️': CircleDot,
  '🌋': Flame,
  '🐲': Swords,
  '🦇': Bird,
  '↺': RotateCcw,
  '↩': Undo2,
  '✓': Check,
  '✗': X,
  '⏳': Timer,
  '🔐': ShieldCheck,
  '←': ArrowLeft,
  '→': ArrowRight,
  '✏️': Pencil,
  '✏': Pencil,
  '＋': Plus,
  '+': Plus,
  '☰': Menu,
  '⚙️': Settings,
  '⚙': Settings,
  '🚪': LogOut,
  '💰': CircleDollarSign,
  '🏅': Medal,
  '🔄': RotateCcw,
  '📅': CalendarDays,
  '📒': BookOpen,
  '🎮': Gamepad2,
  '📱': Smartphone,
  '🍕': Pizza,
  '🎬': Film,
  '🎡': FerrisWheel,
  '🎪': TentTree,
  '🛒': ShoppingCart,
  '💤': Moon,
  '😈': Ghost,
  '⭕': CircleCheckBig,
  '❌': CircleX,
}

interface RealmIconProps {
  name: string
  size?: number
  strokeWidth?: number
  className?: string
  title?: string
}

export function RealmIcon({ name, size = 18, strokeWidth = 1.9, className, title }: RealmIconProps) {
  const Icon = ICONS[name]

  if (!Icon) {
    return (
      <span
        className={className}
        role={title ? 'img' : undefined}
        aria-label={title ?? name}
        aria-hidden={title ? undefined : true}
        style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: size, height: size, fontSize: size * 0.82, lineHeight: 1 }}
      >
        {name}
      </span>
    )
  }

  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden={title ? undefined : true} aria-label={title} />
}
